[env:uno_r4_wifi]
platform = renesas-ra
board = uno_r4_wifi
framework = arduino
lib_deps =
    arduino-libraries/ArduinoBLE
    arduino-libraries/Arduino_LED_Matrix
monitor_speed = 115200
upload_speed = 115200
